sudo: false
language: nix
env:
  matrix:
    - EMACS_CI=emacs-25-3
    - EMACS_CI=emacs-26-3

install:
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)

script:
  - emacs --version
  - make update
  - make clean
  - make compile
  - make package-lint
  - make checkdoc
  - make test
