version: 2.1

# Default actions to perform on each Emacs version
commands:
  default-steps:
    steps:
      - checkout
      - run: make version
      - run: make lint
      - run: make test

# Enumerated list of Emacs versions
jobs:
  test-emacs-25:
    docker:
      - image: silex/emacs:25-dev
        entrypoint: bash
    steps:
      - default-steps

  test-emacs-26:
    docker:
      - image: silex/emacs:26-dev
        entrypoint: bash
    steps:
      - default-steps

  test-emacs-27:
    docker:
      - image: silex/emacs:27-dev
        entrypoint: bash
    steps:
      - default-steps

  test-emacs-master:
    docker:
      - image: silex/emacs:master-dev
        entrypoint: bash
    steps:
      - default-steps

  # coverage:
  #   docker:
  #     - image: silex/emacs:26-dev
  #       entrypoint: bash
  #   steps:
  #     - checkout
  #     - run: make submit-coverage

# Executing in parallel
workflows:
  ci-test-matrix:
    jobs:
      - test-emacs-25
      - test-emacs-26
      - test-emacs-27
      - test-emacs-master
      # - coverage:
      #     requires:
      #     - test-emacs-25
      #     - test-emacs-26
      #     - test-emacs-27
      #     - test-emacs-master
